### ISSUE TITLE
Current issues in 0.0.219.1

### ISSUE THREAD

**Issue by cctbcn** [cctbcn/mchf_github#2]
- Need to add offset in band determination to account for LO's being shifted when frequency translate is active so that the band doesn't change to "Gen" prematurely before and/or after approaching within 6 kHz of the edge of an amateur band.  (Easy to do, just need to remember...)

- TUNE mode in SSB needs to be unified to be a special case of CW TUNE mode so that the sidetone is audible.  As of 0.0.217>=0.0.219.1 the generation of an SSB->TUNE sidetone is impossible if frequency translation is active since the D/A is being fed a frequency of 6750 or 5250 Hz, depending on configuration/sideband.  As with CW/CW-TUNE mode, frequency translation needs to be disabled for SSB->TUNE mode with the appropriate LO shifting taken into account.

- Look into putting a "Center" frequency marker on spectrum display, particularly now that the "translate" mode will move the "center" tuning frequency physically off-center from the display.  This is a bit tricky on the spectrum display itself as doing so would increase the overhead of the spectrum scope if it is within the confines of the graphics itself.  If the marker is located within the field of the bottom-of-the-screen graticule, outside the active area of the spectrum scope, this would greatly reduce overhead.

- At the moment the "2X Magnify" on the spectrum scope is disabled when frequency translate is activated.  It would be "nice" to rewrite this so that when frequency translate was active, the "center" frequency was actually in the center of the screen when "2X Magnify" mode was on.  Not hard to do, just too many things to do!

- The spectrum scope needs to be completely rewritten to use a fixed vertical dB scale rather than the rather confusing, auto-scaling vertical non-logarithmic, non-linear that is used at the moment.  It will likely be necessary to convert the entire spectrum scope processing code to floating point to do this to achieve the needed dynamic range:  Much of it is, already!

LONG TERM ISSUES:

- Determine viable formula for the calculation of RF power from A/D values related to readings from FWD/REV power  sensors.  There is currently a problem in that a DC bias appears on the power sensors due to an apparent artifact in the A/D MUX of the MCU that needs to be investigated:  This bias is inconsistent and tends to "break" the typical formulas that one would normally use - particularly at lower power levels.  FWD power calculation via formulas is possible - which would also make REV power readings possible - on-the-fly VSWR calculations are NOT possible with any reasonable degree of accuracy or consistency across varying power levels!

- The addition of A/B VFO.  Attempts have been made to add A/B VFOs in the past, but this has "broken" the radio completely.  It is believed that one of the culprits has been the "memory leak" issue - possibly a compiler problem - that has been at least partially responsible for thwarting these efforts.  Once an A/B VFO is done, it should be a trivial matter to do things like add SPLIT and frequency memories.

- Solution of the aforementioned "Memory Leak" problem.  At the moment, the (VERY kludgy!) work-around has been to allocate large chunks of RAM in the "audio_driver.c" function in strategic places so that amok memory buffers will (hopefully!) harmlessly spill into unused memory space.  The exact cause - or what is being affected - by this problem is unknown, but it does seem to largely affect the DMA memory and/or memory used for active audio processing.  I have spent many hours trying to track this one down, changing variable types, etc. but have had no luck in affecting it at all.  (Perhaps one of the many, many warnings at compile time might hold a clue - but which one(s)?)

**Comment by edwin-oetelaar** [comment]
https://github.com/cctbcn/mchf_github/blob/96af99cc3b0d52a2d293bd5f3f017e5754a0a8b8/drivers/audio/audio_driver.c#L1034
 
the parameters may not be  in the right order :

arm_lms_norm_f32(&lms2Norm_instance, ads.a_buffer, &lms2_nr_delay[lms2_outbuf], errsig2, ads.a_buffer, psize/2);	// do automatic notch


looks like you (or someone else who wrote this code) got errsig2 and ads.a_buffer mixed up.

/**
   * @brief Processing function for floating-point normalized LMS filter.
   * @param[in] *S points to an instance of the floating-point normalized LMS filter structure.
   * @param[in] *pSrc points to the block of input data.
   * @param[in] *pRef points to the block of reference data.
   * @param[out] *pOut points to the block of output data.
   * @param[out] *pErr points to the block of error data.
   * @param[in] blockSize number of samples to process.
   * @return none.
   */

  void arm_lms_norm_f32(
  arm_lms_norm_instance_f32 * S,
  float32_t * pSrc,
  float32_t * pRef,
  float32_t * pOut,
  float32_t * pErr,
  uint32_t blockSize);

**Comment by cctbcn** [comment]
The parameters are, in fact, correct for a "notch" response.  When used in the manner you suggest the LMS function will converge to provide a bandpass-type response - which is the way the noise reduction works (e.g. converging on the coherent portions of voice energy.)

For the notch response the opposite is needed:  To remove the energy that achieves coherence, hence the use of the "error" output which contains the residual energy - which, by definition, lacks the frequencies on which the function converged.  For this reason the "error" output is that which is sent to the output buffer while the normal output is simply discarded.

It is through appropriate selection of the "mu" factor that one adjusts the convergence rate for either the "noise reduction" or "notch" functions - with "notch" typically acting more quickly and being placed in the signal path after the noise reduction function.

**Comment by edwin-oetelaar** [comment]
You might be right, I have no idea how this code works yet.
I just noticed that the parameters looked strange compared to the other invocations of the function.
